server {
    listen 80;
    server_name your-server.example.com;

    index 404.html;
    root /usr/share/nginx/html;

    location = /deploy/annopilot {
        proxy_pass http://127.0.0.1:9010/deploy/annopilot;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /annopilot-webhook-healthz {
        proxy_pass http://127.0.0.1:9010/healthz;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
