from __future__ import annotations

from typing import Any


APPRAISAL_ENGAGEMENT_TAXONOMIES: dict[str, dict[str, Any]] = {
    "engagement_monogloss": {
        "framework": "appraisal",
        "system": "engagement",
        "dialogic_status": "monogloss",
        "orientation": None,
        "family": "monogloss",
        "subtype": None,
        "path": ["engagement", "monogloss"],
        "default_scope": "proposition",
    },
    "engagement_entertain": {
        "framework": "appraisal",
        "system": "engagement",
        "dialogic_status": "heterogloss",
        "orientation": "expansion",
        "family": "entertain",
        "subtype": None,
        "path": ["engagement", "heterogloss", "expansion", "entertain"],
        "default_scope": "cue",
    },
    "engagement_attribute_acknowledge": {
        "framework": "appraisal",
        "system": "engagement",
        "dialogic_status": "heterogloss",
        "orientation": "expansion",
        "family": "attribute",
        "subtype": "acknowledge",
        "path": ["engagement", "heterogloss", "expansion", "attribute", "acknowledge"],
        "default_scope": "cue",
    },
    "engagement_attribute_distance": {
        "framework": "appraisal",
        "system": "engagement",
        "dialogic_status": "heterogloss",
        "orientation": "expansion",
        "family": "attribute",
        "subtype": "distance",
        "path": ["engagement", "heterogloss", "expansion", "attribute", "distance"],
        "default_scope": "cue",
    },
    "engagement_proclaim_endorse": {
        "framework": "appraisal",
        "system": "engagement",
        "dialogic_status": "heterogloss",
        "orientation": "contraction",
        "family": "proclaim",
        "subtype": "endorse",
        "path": ["engagement", "heterogloss", "contraction", "proclaim", "endorse"],
        "default_scope": "cue",
    },
    "engagement_proclaim_pronounce": {
        "framework": "appraisal",
        "system": "engagement",
        "dialogic_status": "heterogloss",
        "orientation": "contraction",
        "family": "proclaim",
        "subtype": "pronounce",
        "path": ["engagement", "heterogloss", "contraction", "proclaim", "pronounce"],
        "default_scope": "cue",
    },
    "engagement_proclaim_concur": {
        "framework": "appraisal",
        "system": "engagement",
        "dialogic_status": "heterogloss",
        "orientation": "contraction",
        "family": "proclaim",
        "subtype": "concur",
        "path": ["engagement", "heterogloss", "contraction", "proclaim", "concur"],
        "default_scope": "cue",
    },
    "engagement_disclaim_deny": {
        "framework": "appraisal",
        "system": "engagement",
        "dialogic_status": "heterogloss",
        "orientation": "contraction",
        "family": "disclaim",
        "subtype": "deny",
        "path": ["engagement", "heterogloss", "contraction", "disclaim", "deny"],
        "default_scope": "cue",
    },
    "engagement_disclaim_counter": {
        "framework": "appraisal",
        "system": "engagement",
        "dialogic_status": "heterogloss",
        "orientation": "contraction",
        "family": "disclaim",
        "subtype": "counter",
        "path": ["engagement", "heterogloss", "contraction", "disclaim", "counter"],
        "default_scope": "cue",
    },
}

